service:
  name: config-server
  version: 1.0.0-SNAPSHOT
  env: dev
server:
  port: 8000
  base-url: http://localhost:8000/v1
  session-duration: 3600
  cors:
    allowed-origins: '*'
    supported-methods: 'GET,POST,PUT,DELETE,OPTIONS'
datasource:
  type: sqlite3
  location: ./data/data.db